@startuml
left to right direction
actor user
rectangle productProduction{
  usecase "Cadastrar Produtos" as cadProd
  usecase "Cadastrar Produção" as cadProdFab
  usecase "Validar Produto" as valProd
  usecase "Lista Produtos Fabricados" as listProdFab
  usecase "Lista Produtos a Fabricar" as listProdA_Fab
  usecase "Cadastrar Pedido" as cadPed
}
user --> cadProd
user --> cadProdFab
user --> cadPed
cadProd <. valProd: include
cadProdFab <. listProdFab : include
cadPed <. listProdA_Fab : include
@enduml